var ib_invoice_data = {
  "{company_logo}"          : "@@LOGO", // base64 encoded data URI of PNG image
  "{company_name}"          : "Petak marketing",
  "{company_address}"       : "Mladena Kerstnera 42",
  "{company_city_zip_state}": " ● 10410, Velika Gorica",
  "{company_phone_fax}"     : "+385 91 555 3153",
  "{company_email_web}"     : " ● www.petak.marketing ● renata@petakmarketing.hr",
  "{payment_info1}"         : "&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Payment details:",
  "{payment_info2}"         : "&nbsp; &nbsp; &nbsp; &nbsp; ● ACC 123006705",
  "{payment_info3}"         : "&nbsp; &nbsp; ● IBAN US100000060345",
  "{payment_info4}"         : "● SWIFT BOA447",
  "{payment_info5}"         : "",
  "{issue_date_label}"      : "Datum izdavanja:",
  "{issue_date}"            : "",
  "{net_term_label}"        : "Net:",
  "{net_term}"              : 21,
  "{due_date_label}"        : "Datum dospijeća:",
  "{due_date}"              : "",
  "{currency_label}"        : "Currency:",
  "{currency}"              : "HRK",
  "{po_number_label}"       : "P.O. #",
  "{po_number}"             : "1-1-1",
  "{bill_to_label}"         : "Za:",
  "{client_name}"           : "Slate Rock and Gravel Company",
  "{client_address}"        : "222 Rocky Way",
  "{client_city_zip_state}" : "30000 Bedrock, Cobblestone County",
  "{client_phone_fax}"      : "+555 7 123-5555",
  "{client_email}"          : "fred@slaterockgravel.bed",
  "{client_other}"          : "Attn: Fred Flintstone",
  "{invoice_title}"         : "RAČUN",
  "{invoice_number}"        : "#1-1-1",
  "{item_row_number_label}" : "",
  "{item_description_label}": "Naziv",
  "{item_quantity_label}"   : "Količina",
  "{item_price_label}"      : "Cijena",
  "{item_discount_label}"   : "Popust",
  "{item_tax_label}"        : "PDV",
  "{item_line_total_label}" : "Ukupno",
  "{item_row_number}"       : "",
  "{item_description}"      : "",
  "{item_quantity}"         : "",
  "{item_price}"            : "",
  "{item_discount}"         : "",
  "{item_tax}"              : "",
  "{item_line_total}"       : "",
  "{amount_subtotal_label}" : "Iznos:",
  "{amount_subtotal}"       : "",
  "{tax_name}"              : "PDV:",
  "{tax_value}"             : "",
  "{amount_total_label}"    : "Ukupno:",
  "{amount_total}"          : "",
  "{amount_paid_label}"     : "Paid:",
  "{amount_due_label}"      : "Ukupno za platiti:",
  "{amount_due}"            : "",
  "{terms_label}"           : "Hvala!",
  "{terms}"                 : "&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Fred, thank you very much. We really appreciate your business.<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Please send payments before the due date.",

  // Settings
  "date_format"             : "mm/dd/yyyy", // One of dd/mm/yyyy, dd-mm-yyyy, mm/dd/yyyy, mm-dd-yyyy
  "currency_position"       : "left", // One of left or right
  "default_columns"         : ["item_row_number", "item_description", "item_quantity", "item_price", "item_discount", "item_tax", "item_line_total"],
  "default_quantity"        : "1",
  "default_price"           : "0",
  "default_discount"        : "0",
  "default_tax"             : "0",
  "default_number_rows"     : 3,
  "auto_calculate_dates"    : true,
  "load_items"              : true,
  "invoicebus_fineprint"    : true,

  // Items
  "items": [
    {
      "item_description" : "Frozen Brontosaurus Ribs",
      "item_quantity"    : "2",
      "item_price"       : "120",
      "item_discount"    : "",
      "item_tax"         : "2%"
    },
    {
      "item_description" : "Mammoth Chops",
      "item_quantity"    : "14",
      "item_price"       : "175",
      "item_discount"    : "-10%",
      "item_tax"         : "5%"
    },
    {
      "item_description" : "",
      "item_quantity"    : "",
      "item_price"       : "",
      "item_discount"    : "",
      "item_tax"         : ""
    }
  ]
};
